version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///./todos.db
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DEBUG: "True"
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3000
    volumes:
      - .:/app
      - sqlite_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data: